### ISSUE TITLE
Trying to use this, can't get it to install and work

### ISSUE THREAD

**Issue by csterritt** [robinpowered/react-native-screen-brightness#2]
Hi -- I'd like to contribute to the installation guide.

I tried just adding the javascript code, and it didn't work, failing in the debugger with:

    Cannot read property 'setBrightness' of undefined

So I'm guessing what to do here :-) based on various other react-native plugins.

So I've changed `android/app/build.gradle` to have:

    --- a/android/app/build.gradle
    +++ b/android/app/build.gradle
    @@ -131,4 +131,5 @@ dependencies {
         compile fileTree(dir: "libs", include: ["*.jar"])
         compile "com.android.support:appcompat-v7:23.0.1"
         compile "com.facebook.react:react-native:0.20.+"
    +    compile project(":react-native-screen-brightness")
     }

Added:

    import com.robinpowered.react.ScreenBrightness.ScreenBrightnessPackage;

to my `MainActivity.java` file, which also has:

    @@ -51,7 +53,8 @@ public class MainActivity extends ReactActivity {
         @Override
         protected List<ReactPackage> getPackages() {
           return Arrays.<ReactPackage>asList(
    -        new MainReactPackage()
    +        new MainReactPackage(),
    +        new ScreenBrightnessPackage(this)
           );
         }
     }

Added to `android/settings.gradle`:

    include ':react-native-screen-brightness'
    project(':react-native-screen-brightness').projectDir = new File(settingsDir, '../node_modules/react-native-screen-brightness/android')

Finally, my `index.android.js` file has:

    import { NativeModules } from "react-native";
    const { SystemBrightness } = NativeModules;
    //...
    SystemBrightness.setBrightness(0.75);

This all compiles fine, but I still get the `Cannot read property 'setBrightness' of undefined` error.

Any help much appreciated!

**Comment by ajwhite** [comment]
A couple things here - firstly, the Native Module name is `ScreenBrightness` - so you want

```js
import {NativeModules} from 'react-native';
const {ScreenBrightness} = NativeModules;
//...
ScreenBrightness.setBrightness(0.75);
```


But secondly, I'm surprised your build had compiled - `ScreenBrightnessPackage` currently requires [two parameters](https://github.com/robinpowered/react-native-screen-brightness/blob/master/android/src/main/java/com/robinpowered/react/ScreenBrightness/ScreenBrightnessPackage.java#L20)


```java
new ScreenBrightnessPackage(this, 1234)
```

The second parameter is a request code for prompting the `WRITE_SETTINGS` permissions request (can be any number). This lets the module adjust the system brightness, as well as the application brightness. This is something we can eventually make optional, but at this time it's part of the constructor.

**Comment by csterritt** [comment]
Wow, ScreenBrightness instead of SystemBrightness?  That's not an embarrassing mistake at all :-)

Anyway, I must be using the wrong version.  With the extra constructor argument, I get:

```
/Volumes/Second/Chris/hacks/magic_mirror/react_native/MagicMirror/android/app/src/main/java/com/magicmirror/MainActivity.java:57: error: constructor ScreenBrightnessPackage in class             ScreenBrightnessPackage cannot be applied to given types;
            new ScreenBrightnessPackage(this, 1234)
            ^
      required: Activity
      found: MainActivity,int
      reason: actual and formal argument lists differ in length
    1 error 
```

However, the cool thing is that in spite of that, it works!  Thanks!

**Comment by ajwhite** [comment]
Carry on then! it looks like we have not yet published the new approach to NPM, so you're good :smile:
