### ISSUE TITLE
Is there any update for the React Native 0.60 AutoLinking?

### ISSUE THREAD

**Issue by SnehalAgrawal** [robinpowered/react-native-screen-brightness#33]
Have an example here [Control Device Brightness from React Native App](https://aboutreact.com/react-native-screen-brightness/) using this library but it's completely not running after the update of React Native. I have done the custom changed in the Android files also but everything is worthless now. Is there any maintainer of this library?

**Comment by mars-lan** [comment]
https://github.com/robinpowered/react-native-screen-brightness/pull/37
