### ISSUE TITLE
AndroidX Support?

### ISSUE THREAD

**Issue by clevertree** [robinpowered/react-native-screen-brightness#36]
Looks like i'm being forced to upgrade to the AndroidX support library. This means I have to modify the imports to get it to compile. Is there an NPM version that can be used with AndroidX?

> Task :react-native-screen-brightness:compileReleaseJavaWithJavac FAILED
210 actionable tasks: 209 executed, 1 up-to-date
/Users/vsts/agent/2.158.0/work/1/s/node_modules/react-native-screen-brightness/android/src/main/java/com/robinpowered/react/ScreenBrightness/ScreenBrightnessModule.java:10: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
1 error

Thanks a bunch!

**Comment by christophermark** [comment]
@clevertree can you test to see if this diff solves things for you?
https://github.com/robinpowered/react-native-screen-brightness/pull/34

I've been busy lately and haven't had time to test this on a fresh React Native 60+ project myself.

**Comment by clevertree** [comment]
@christophermark took me a bit to figure out how to 
$ npm install git+https://github.com/robinpowered/react-native-screen-brightness#pull/37/head

After that, I removed the integer parameter from 
        new ScreenBrightnessPackage(),

and it appears to be working on my simulator. I'm going to test on hardware now. Thanks again!

**Comment by mars-lan** [comment]
https://github.com/robinpowered/react-native-screen-brightness/pull/37
