### ISSUE TITLE
 Not supporting RN 0.29 

### ISSUE THREAD

**Issue by KevinHu2014** [robinpowered/react-native-screen-brightness#7]
Hi,
it seems not supporting on RN 0.29.
Any ideas on how to fix it?

**Comment by nikita-usatenko** [comment]
@ajwhite Hi!

Any information on adding RN 0.29 support?

Thanks

**Comment by ajwhite** [comment]
Certainly want to get this up to speed with `0.29` ASAP -- does anyone have information on the problems that have been encountered?

**Comment by nikita-usatenko** [comment]
Activity cannot be passed as a parameter in MainApplication.java.

```java
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new ScreenBrightnessPackage(this)
    );
}
```

**Comment by ajwhite** [comment]
Hey folks, it looks like an unreleased tag, `0.2.0`, no longer requires passing the `Activity` instance, https://github.com/robinpowered/react-native-screen-brightness/blob/v0.2.0/android/src/main/java/com/robinpowered/react/ScreenBrightness/ScreenBrightnessPackage.java

Will publish after verifying a few things on the latest RN builds

**Comment by Naoto-Ida** [comment]
Hi, any progress on this??

**Comment by RiadySantoso82** [comment]
at your MainApplication.java, in line new ScreenBrightnessPackage() change to new ScreenBrightnessPackage(1)

**Comment by christophermark** [comment]
With #37 we now have an overloaded constructor without the requirement of an integer. Closing this
